# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-28 00:58


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestMainModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foo', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TestOneToOneModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bar', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TestRelatedModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baz', models.TextField()),
                ('main_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djanx.TestMainModel')),
            ],
        ),
        migrations.AddField(
            model_name='testmainmodel',
            name='o2o',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='djanx.TestOneToOneModel'),
        ),
    ]
