# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-28 19:08


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djanx', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testmainmodel',
            name='o2o',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='djanx.TestOneToOneModel'),
        ),
    ]
